name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Lint
      run: make lint

  test:
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        go:
        - 1.19.x
        include:
        - platform: ubuntu-latest
          go: 1.19.x
          goarch: '386'
        - platform: macos-latest
          go: 1.19.x
        - platform: windows-latest
          go: 1.19.x
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Test
      run: make test
      env:
        GOARCH: ${{ matrix.goarch }}
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERAGE_VERSION: 1.19
  test32bit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Test on 32-bit platform
      run: |
        docker build --platform=linux/386 -t test_32bit -f Dockerfile.test .
        docker run --platform=linux/386 --rm test_32bit go test ./...
