name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.19.x
    - name: Lint
      run: make lint

  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ v1.19.x ]
        goarch: [ amd64, '386' ]
        exclude:
          - platform: macos-latest
            goarch: '386'
          - platform: windows-latest
            goarch: '386'
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.version }}
        architecture: ${{ matrix.goarch }}
    - name: Test
      run: make test
      env:
        GOARCH: ${{ matrix.goarch }}
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERAGE_VERSION: '1.19'
